config/routes.rb
Rails.application.routes.draw do
  root "show#v1"

  get 'show/v1', to: 'show#v1', as: 'v1'
  get 'show/v2', to: 'show#v2', as: 'v2'
  get 'show/v3', to: 'show#v3', as: 'v3'

  resources :banners
end

app/models/banner.rb
class Banner < ActiveRecord::Base
	include Scopes

	validates :banner_type, presence: true
end

app/models/concerns/scopes.rb
module Scopes
	extend ActiveSupport::Concern

	included do
		scope :asc,  -> { order(id: :asc) }
		scope :desc, -> { order(id: :desc) }
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController

	before_action :set_banner, only: [:edit, :update, :destroy]

  def index
    @banners = Banner.asc
  end

  def new
    @banner = Banner.new
  end

  def create
    @banner = Banner.new banner_params

    if @banner.save
      redirect_to banners_path , notice: "Banner was succesfully created."
    else
      render :new
    end
  end

  def edit; end

  def update
    @banner.update! banner_params

    redirect_to banners_path, notice: "Banner was successfully updated."
  end

  def destroy
  	@banner.destroy
  	redirect_to banners_url, notice: "Banner was successfully destroyed."
  end

  private

  def set_banner
    @banner = Banner.find(params[:id])
  end

  def banner_params
    params.require(:banner).permit([:name, :top, :right, :bottom, :left, :banner_type, :link])
  end
end

app/controllers/show_controller.rb
class ShowController<ApplicationController
  def v1
  end

  def v2
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Widget

  def active_menu_item current
    'active' if controller_name == current.to_s
  end

  def active_aside_item current
    'active' if action_name == current.to_s
  end
end

app/helpers/banners_helper.rb
module BannersHelper
	def checker place
		image_tag 'checker.gif' if place
	end
end

app/helpers/widget.rb
module Widget
  def banner_widget pos
    src = get_src( pos )
    content = render_template( pos, src )
    wrap_content( pos, content )
  end

  def get_src pos
    case pos
    when :top
      { type: :banner, src: '/img/banner-leaderboard-1.png' }
    when :right
      { type: :banner, src: '/img/banner-vertical-1.gif' }
    when :bottom
      { type: :banner, src: '/img/banner-leaderboard-1.jpg' }
    when :middle
      { type: :banner, src: '/img/banner-middle-1.gif' }            
    end
  end

  def render_template pos, src
    case pos
    when :top
      top_banner_template( src )
    when :right
      right_banner_template( src )
    when :bottom
      bottom_banner_template( src )      
    when :middle
      middle_banner_template( src )      
    end
  end

  def top_banner_template src
    case src[:type]
    when :banner
      content = link_to image_tag(src[:src], size: '728x90', alt: 'top-banner'), 'http://www.example-top.com/', target: '_blank'
    end
  end

  def right_banner_template src
    case src[:type]
    when :banner
      content = link_to image_tag(src[:src], size: '120x240', alt: 'right-banner'), 'http://www.example-right.com/', target: '_blank'    
    end
  end

  def bottom_banner_template src
    case src[:type]
    when :banner
      content = link_to image_tag(src[:src], size: '728x90', alt: 'botttom-banner'), 'http://www.example-bottom.com/', target: '_blank'    
    end
  end

  def middle_banner_template src
    case src[:type]
    when :banner
      content = link_to image_tag(src[:src], size: '300x300', alt: 'middle-banner'), 'http://www.example-middle.com/', target: '_blank'    
    end
  end

  def wrap_content pos, content
    case pos
    when :top
      "<div class=\"banner top-banner\">#{content}</div>".html_safe      
    when :right
      "<div class=\"banner right-banner\">#{content}</div>".html_safe      
    when :bottom
      "<div class=\"banner bottom-banner\">#{content}</div>".html_safe
    when :middle
      "<div class=\"banner middle-banner\">#{content}</div>".html_safe      
    end
  end
end


#   content = widget_content( position )
#   def widget_content position
#     get
#     case type
#     when :banner
#       content = link_to image_tag('/img/banner-leaderboard-1.png', size: '728x90', alt: 'top-banner'), 'http://www.example-top.com/', target: '_blank'
#     when :flash
#       flash = "<object type='application/x-shockwave-flash' data='/swf/banner-flash-1.swf' width='728' height='90'></object>"
#       content = link_to 'http://www.example-top.com/', target: '_blank' do
#         flash.html_safe
#       end
#     when :html
#       content = "<h1>Hello world banner</h1>"
#     end
#   end

#   def widget_template position, content
#     case position
#     when :top
#       "#{content}".html_safe      
#     when :right
#       "#{content}".html_safe      
#     end
#   end
# end

app/views/banners/_form.html.haml
= form_for @banner do |f|
	= render partial: '/layouts/items/errors', locals: { object: @banner }
	
	<!-- ... -->
	<!-- Type div -->
	<!-- ... -->
	.form-group#radio_banner_type
		%label Type:
		= f.radio_button :banner_type, :banner
		= f.label :banner_type, 'Banner', value: :banner
		= f.radio_button :banner_type, :flash
		= f.label :banner_type, 'Flash', value: :flash
		= f.radio_button :banner_type, :html
		= f.label :banner_type, 'HTML', value: :html

	<!-- ... -->
	<!-- Place div -->
	<!-- ... -->
	.form-group#checkbox_place
		%label Place:
		= f.check_box :top
		= f.label :top, 'Top'
		= f.check_box :right
		= f.label :right, 'Right'
		= f.check_box :bottom
		= f.label :bottom, 'Bottom'
		= f.check_box :left
		= f.label :left, 'Left'

	.form-group
		= f.label :link
		= f.text_field :link, class: 'form-control'

	.form-group
		= f.label :html
		= f.text_area :html, cols: 60, rows: 5, class: 'form-control'


	.form-group
		= f.submit class: 'btn btn-primary'

app/views/banners/edit.html.haml
%h1 Edit banner

= render 'form'

app/views/banners/index.html.haml
%h1 List of Banners

%p
:preserve
  <ul class="nav nav-tabs" id="banners-tab" role="tablist" data-tabs="tabs">
    <li class="active">
      <a href="#banner" role="tab" data-toggle="tab" >Banner</a>
    </li>
    <li>
      <a href="#flash"  role="tab" data-toggle="tab" >Flash</a>
    </li>
    <li>
      <a href="#html"   role="tab" data-toggle="tab" >HTML</a>
    </li>
  </ul>

  <div class="tab-content">
  	<div class="tab-pane active" id="banner">
  		<span>Banner</span>
  	</div>
    <div class="tab-pane" id="flash">
      <span>Flash</span>
    </div>
  	<div class="tab-pane" id="html">
  		<span>Html</span>
  	</div>
  </div>


/ %table.table.table-striped
/ 	%thead
/ 		%th Type
/ 		%th Top
/ 		%th Right
/ 		%th Bottom
/ 		%th Left
/ 		%th Link
/ 	%tbody
/ 	- @banners.each do |banner|
/ 		%tr
/ 			%td= banner.banner_type

/ 			%td= checker banner.top
/ 			%td= checker banner.right
/ 			%td= checker banner.bottom
/ 			%td= checker banner.left

/ 			%td= banner.link
/ 			%td
/ 				= link_to image_tag('pencil.png'), edit_banner_path( banner )
/ 				= link_to image_tag('trash.png'), banner, method: :delete, data: { confirm: 'Are you sure?'}

app/views/banners/new.html.haml
%h1 New banner

= render 'form'

app/views/layouts/application.html.haml
!!! 5
%html{ lang: :en }
  %head
    %title Banner
    = stylesheet_link_tag    :application
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    .container
      = render partial: 'layouts/items/header'    
      .row
        .col-md-4
          = render partial: 'layouts/items/aside_menu'  
        .col-md-20
          = render partial: 'layouts/items/notice'
          = render partial: 'layouts/items/article'

app/views/layouts/items/_article.html.haml
.container
  %article
    .row
      .col-md-20
        = yield :top_banner
    .row
      .col-md-17
        = yield :title
        = yield      
      .col-md-3
        = yield :right_banner
    .row
      .col-md-20
        = yield :bottom_banner

app/views/layouts/items/_aside_menu.html.haml
%ul.nav.nav-pills.nav-stacked#aside-menu
  - case controller_name
    - when 'show'
      %li{ class: active_aside_item(:v1) }
        = link_to "v1", v1_path
      %li{ class: active_aside_item(:v2) }
        = link_to "v2", v2_path
      %li{ class: active_aside_item(:v3) }
        = link_to "v3", '#'
    - when 'banners'
      %li= link_to 'List of banners', banners_path
      %li= link_to 'New banner', new_banner_path

app/views/layouts/items/_errors.html.haml
-if object.errors.any? 
	.alert.alert-danger
		= "#{pluralize(object.errors.count,'error')} prohibited this thing from being saved: "
		%ul
			- object.errors.full_messages.each do |msg|
				%li= "#{msg}"

app/views/layouts/items/_header.html.haml
%nav.navbar{ role: :navigation }
  .container-fluid
    =link_to 'Banner Machin', root_path, class: 'navbar-brand'
    %ul.nav.nav-pills
      %li{ class: active_menu_item(:show) }
        = link_to 'Show', v1_path
      %li{ class: active_menu_item(:banners) }
        = link_to 'Control', banners_path

app/views/layouts/items/_notice.html.haml
- flash.each do |name, msg|
	= content_tag :div, msg, class: 'alert alert-info'

app/views/show/v1.html.haml
- content_for :title do
  %h3 Banner widget test

- content_for :top_banner do
  = banner_widget :top

- content_for  :right_banner do
  = banner_widget :right

- content_for  :bottom_banner do
  = banner_widget :bottom

= banner_widget :middle

%p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.

%p Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo.

app/views/show/v2.html.haml
hello from show#v2